### ISSUE TITLE
Better explain value of achieved scores

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/tune-twins#64]
Reviewers seem to miss the point about the scores. It's not so much about being on par
with the alignment method, but more about the ease of feature selection, and, crucially,
the efficiency of the system after training.

**Comment by emanjavacas** [comment]
They say they are not overwhelmed by the results. I dunno but 5 points overall MAP improvement seems pretty solid to me. I guess people are expecting massive improvements from NNs, but that's not really happening suddenly in any fields. Even NMT took a long time until the difference started to be large. I also agree developing a model like this is beneficial beyond the improvement.

**Comment by emanjavacas** [comment]
I'd close this.

**Comment by fbkarsdorp** [comment]
I agree. We're not celebrating our results too much, yet also don't frame it as a negative result, which it clearly isn't. Closing.
