### ISSUE TITLE
Give better explanation for results alignment on seen data set

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/tune-twins#66]
We know this is simply an artifact of the data. We could go into a more in depth analysis,
but I'm not sure it's worth the effort, and I doubt we have enough time to finish that
satisfactorily. So, I'd suggest to add a line commenting on this result, and explaining
that this is most likely due to an artifact in the sampling strategy.

**Comment by emanjavacas** [comment]
Yes. Good idea. It's way less confusing now. The distinction seen/unseen is irrelevant for the alignment method anyway. Fine by me.

**Comment by fbkarsdorp** [comment]
Great. Closing then.
