### ISSUE TITLE
Significance testing

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/tune-twins#67]
Two reviewers ask to test whether the performance differences are significant. I don't
want to do this. :) It gives the wrong suggestion either way, and I believe a qualitative
error analysis would be much more valuable than some arbitrary p-value thingy. This also
relates to the issue of better explaining the values of the achieved scores: Even if the
two system would perform exactly the same, the NN approach is still valuable.

**Comment by emanjavacas** [comment]
And also it's a 5 MAP points difference over almost 2k instances. I'd be surprised if you don't get a p<0.001 at least. But yes, the error analysis would be more informative. Future work in any case.
