### ISSUE TITLE
Efficiency issues

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/tune-twins#68]
Third point of reviewer 1. I don't think we have enough space to deal with this, nor do I
believe it's really important. The blackbox argument is a little too simple, but perhaps
we can make it more clear that we want to open up certain aspects in future work?

**Comment by emanjavacas** [comment]
It's pretty much cliche-criticism of Neural networks... in my opinion it's beyond the scope of the paper.

**Comment by fbkarsdorp** [comment]
My thoughts exactly. Closing.
