### ISSUE TITLE
Employ LambdaLoss

### ISSUE THREAD

**Issue by fbkarsdorp** [fbkarsdorp/tune-twins#72]
Interesting thought, but something for another paper, I'd say.

**Comment by fbkarsdorp** [comment]
I think we can all agree that with the deadline rapidly approaching, this is no longer feasible (if it ever was). Closing.

**Comment by emanjavacas** [comment]
I am not very confident with this lambdaloss thingy, I am gonna check it out for reference, but indeed I don't think there is time, and we should first assess whether it makes sense....
